### ISSUE TITLE
Sign In causes a blank workspace to appear

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/SignIn#12] opened 2016-03-24 14:27 UTC
Current implementation of the "Sign In" and "Sign Out" button results in a blank workspace appearing in Launcher.

For example:

![bug](https://cloud.githubusercontent.com/assets/566463/14019814/cc9b04cc-f1d4-11e5-980c-e21ed876e9fa.gif)

@miyconst any idea how to implement it better?

**Comment by malx122** [comment] 2016-03-24 14:31
This is the same issue that I'm struggling with in my app for the moment. There is no way of calling an url inside the session without switching to that apps workspace...

**Comment by miyconst** [comment] 2016-03-25 13:19
The problem is that Launcher catches all of the requests and creates a new workspace for it.

I don't like the idea of having workspaces at all, and would replace it with single `CurrentPage` partial. This does not solve the request filtering issue though.

There is a `HandlerLevel` property in `HandleOptions` with the following values:

```cs
public enum HandlerLevels {
    DefaultLevel = 0,
    ApplicationLevel = 1,
    ApplicationExtraLevel = 2
}
```

There is no comments of what it means, but maybe we can somehow mark handlers which should not be caught by launcher?

This particular case with SignIn app can be solved by marking the non-ui handlers with:

```
new HandlerOptions() { SkipRequestFilters = true }
```

**Comment by warpech** [comment] 2016-03-25 18:46
> There is no comments of what it means, but maybe we can somehow mark handlers which should not be caught by launcher?

This is not very clear and should be explained better. Value `0` means an external request. Values `1` and above mean a `Self.GET` request. In case of the OP problem, `HandleLevel` value equals `0`, because it is an external request from the browser.

> This particular case with SignIn app can be solved by marking the non-ui handlers with: `new HandlerOptions() { SkipRequestFilters = true }`

Thanks, this is actually a very good solution! Any potential drawbacks?

```cs
            Handle.GET<string, string>("/signin/partial/signin/{?}/{?}", HandleSignIn, new HandlerOptions() { SkipRequestFilters = true });
            Handle.GET("/signin/partial/signin/", HandleSignIn);
            Handle.GET("/signin/partial/signin", HandleSignIn);
            Handle.GET("/signin/partial/signout", HandleSignOut, new HandlerOptions() { SkipRequestFilters = true });
```

In future I would like to have a chance to control this by applying middleware more selectively. @per-samuelsson is working on that: https://github.com/Starcounter/Starcounter/issues/3444 (and related issues, linked at the bottom)

**Comment by miyconst** [comment] 2016-03-25 18:56
>Thanks, this is actually a very good solution! Any potential drawbacks?

The only drawback is that other potentially required filters will also be skipped.

**Comment by warpech** [comment] 2016-03-25 19:10
> The only drawback is that other potentially required filters will also be skipped.

I think that an app should never depend on filters added by another app. Filters should be used as a progressive enhancement. Do you agree?

**Comment by miyconst** [comment] 2016-03-25 20:35
Agree, but this does not solve the issue.

Let's assume that we have another app which does something cool things via request filter. Now an app disables the filter, then it won't work.

**Comment by miyconst** [comment] 2016-04-07 10:57
@warpech do you think we can go with `SkipRequestFilters = true` for time being. Something working is better than nothing, even though it's not perfect.

**Comment by warpech** [comment] 2016-04-07 10:59
I agree

**Comment by miyconst** [comment] 2016-04-07 11:36
Fixed and released in `3.2.0`. SignIn is no longer causing the blank screen, closing this issue.

Skipping only Luancher filters should be tracked in another issue.

**Closed by miyconst** 2016-04-07 11:36 UTC

**Comment by warpech** [comment] 2016-04-07 11:42
Could you also fix this in GoogleSignIn? https://github.com/StarcounterSamples/GoogleSignIn/issues/8

**Comment by miyconst** [comment] 2016-04-07 11:46
Will do so, once I get some free time.
